### PR TITLE
Update simple-clock-card.js

### PR DESCRIPTION
**Pull request by GeekDoc**
I believe I have the code for adding a leading zero option.

### CODE REVIEW

**Comment by fufar** [comment]
Cant test this PR becouse of using 24format time, so if you test it and all was ok - im ready to merge :)

**Comment by GeekDoc** [comment]
I'm trying to figure out how to test.  I replace simple-clock-card.js in my configuration, but it doesn't seem to affect my current dashboard.
Let me figure out how to test properly before I vouch for it confidently.

**Comment by fufar** [comment]
i think you need to clear cache and you can check in browser dev tools if you use new version or old

**Comment by fufar** [comment]
@GeekDoc did you manage to check changes?

**Comment by LordMike** [comment]
Looks like it’ll work (untested). Looking forward to it :)

**Comment by fufar** [comment]
ok, lets try:)

**Pull request merged**
